### ISSUE TITLE
[BUG] "출석도장"채널이 아닌 곳에서 이루어진 공부기록

### ISSUE THREAD

**Issue by comnamu18** [comnamu18/discord_study_bot#13]
comnamu18 — 오늘 오후 8:42
!hi
PythonChatBot
봇
 — 오늘 오후 8:42
2021-08-05 20:42:23 : 안녕하세요 comnamu18님!
comnamu18 — 오늘 오후 8:42
!list
PythonChatBot
봇
 — 오늘 오후 8:42
('wraithkim', 3, 1, 'NULL', '2021-08-05 20:01:25')
('comnamu18', 0, 0, '2021-08-05 20:42:23', 'NULL')
comnamu18 — 오늘 오후 8:42
!bye
PythonChatBot
봇
 — 오늘 오후 8:42
2021-08-05 20:42:28 :안녕히가세요 comnamu18님!
comnamu18 — 오늘 오후 8:42
!list
PythonChatBot
봇
 — 오늘 오후 8:42
('wraithkim', 3, 1, 'NULL', '2021-08-05 20:01:25')
('comnamu18', 5, 1, 'NULL', '2021-08-05 20:42:28')

디코 기록 전문인데 다른 채널에서 이루어진 기록이 남아있음
디스코드 토큰을 공유하게 되면서 생긴 문제 같은데,message 채널 소스보고 특정 소스 아니면 reject시키는 기능 필요하다 여겨짐

**Comment by WraithKim** [comment]
아냐 걍 똑같은 봇에 명령을 내렸으니 내가 추가한 스터디 기록이 남은거임. 버그 아님.
